### ISSUE TITLE
Shall there be `ZERO` and maybe `ONE` associated consts for easy creation of specific values?

### ISSUE THREAD

**Issue by vi** [LPGhatguy/nonmax#14]
`Default::default()` partially covers `ZERO` (for non-const), but the const would still be more readable.

**Comment by LPGhatguy** [comment]
I'm very fond of these constants in `glam`, the math library I've been using in projects for awhile. There's no parallel in the standard library (which is kind of weird, isn't it?) but I'd be open to adding these!
